language: objective-c
env:
  matrix:
   - DESTINATION='name=iPhone 4S,OS=8.1'
   - DESTINATION='name=iPhone 5,OS=8.1'
   - DESTINATION='name=iPhone 6,OS=8.1'
   - DESTINATION='name=iPhone 6 Plus,OS=8.1'
   - DESTINATION='name=iPad 2,OS=8.1'
   - DESTINATION='name=iPad Retina,OS=8.1'
   - DESTINATION='name=iPad Air,OS=8.1'
script:
  - xcodebuild -project RMDateSelectionViewController-Demo.xcodeproj -scheme RMDateSelectionViewController-Demo -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -project RMDateSelectionViewController-Demo.xcodeproj -scheme RMDateSelectionViewController-Demo -destination '$DESTINATION'
